---
name: 'Release with submodules'
description: 'Add a release asset containig source code with submodules'
inputs:
  my-token:
    description: 'My PAT'
    required: true
runs:
  using: "composite"
  steps:
    - id: repository-path
      shell: bash
      run: echo "repository-path=${{ format('./{0}', github.event.repository.name) }}" >> $GITHUB_OUTPUT
    - id: set-to-https
      shell: bash
      run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
    - uses: actions/checkout@v4
      with:
        path: ${{ steps.repository-path.outputs.repository-path }}
        submodules: 'recursive'
        token: ${{ inputs.my-token }}
        persist-credentials: false
    - id: create-tar-file
      uses: uclahs-cds/tool-Nextflow-action/tar-with-submodules@latest
      with:
        repository-directory: ${{ steps.repository-path.outputs.repository-path }}
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.create-tar-file.outputs.tar-file-path }}
        token: ${{ inputs.my-token }}
