---
name: 'Release with submodules'
description: 'Add a release asset containig source code with submodules'
inputs:
  my-token:
    description: 'My PAT'
    default: ${{ secrets.MYPAT }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        path: ${{ format('./{0}', github.event.repository.name) }}
        submodules: 'recursive'
        token: ${ inputs.my-token }
    - id: create-tar-file
      uses: uclahs-cds/tool-Nextflow-action/tar-with-submodules@v1.0.0-rc.1
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.create-tar-file.outputs.tar-file-path }}
