---
name: 'Release with submodules'
description: 'Add a release asset containig source code with submodules'
inputs:
  my-token:
    description: 'My PAT'
    required: true
runs:
  using: "composite"
  steps:
    - id: repository-path
      shell: bash
      run: echo "::set-output name=repository-path::${{ format('./{0}', github.event.repository.name) }}"
    - uses: actions/checkout@v3
      with:
        path: ${{ steps.repository-path.outputs.repository-path }}
    - name: Checkout submodules using a PAT
      shell: bash
      run: |
        cd ${{ steps.repository-path.outputs.repository-path }}
        if [[ -f .gitmodules ]]
        then
          git config --file .gitmodules --get-regexp url | while read url; do
            git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ inputs.my-token }}:${{ inputs.my-token }}@github.com\//")
          done
          git submodule sync
          git submodule update --init --recursive
        fi
    - id: create-tar-file
      uses: uclahs-cds/tool-Nextflow-action/tar-with-submodules@v1.0.0-rc.1
      with:
        repository-directory: ${{ steps.repository-path.outputs.repository-path }}
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.create-tar-file.outputs.tar-file-path }}
        token: ${{ inputs.my-token }}
