---
name: 'Create tar with submodules'
description: 'Create compressed tar of repository with submodules'
inputs:
  repository-directory:
    description: 'Path to repository directory for compressing'
    required: true
outputs:
  tar-file-path:
    description: 'Compressed tar with submodules'
    value: ${{ steps.compress-repository.outputs.tar-file-path }}
runs:
  using: "composite"
  steps:
    - id: compress-repository
      shell: bash
      run: |
        tar -czvf source_code_with_submodules.tar.gz ${{ inputs.repository-directory }}
        echo "tar-file-path=$(realpath source_code_with_submodules.tar.gz)" >> $GITHUB_OUTPUT
