---
name: Update image in GHCR

run-name: >
  ${{
    github.event_name == 'delete' && format(
      'Delete `{0}{1}`',
      github.event.ref_type == 'branch' && 'branch-' || '',
      github.event.ref
    )
    || github.ref == 'refs/heads/main' && 'Update `dev`'
      || format(
        'Update `{0}{1}`',
        !startsWith(github.ref, 'refs/tags') && 'branch-' || '',
        github.ref_name
      )
  }} docker tag

on:
  push:
    branches-ignore: ['gh-pages']
    tags: ['v*']
  delete:

jobs:
  push-or-delete-image:
    runs-on: ubuntu-latest
    name: Update GitHub Container Registry
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        nextflow_version:
          - 23.10.0
          - 24.10.4

    steps:
      - uses: actions/checkout@v4
      - name: Get date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - uses: uclahs-cds/tool-Docker-action@v2
        with:
          metadata-file: run-nextflow-tests/docker-metadata.yaml
          file: run-nextflow-tests/Dockerfile-${{ nextflow_version }}
          context: run-nextflow-tests
          custom-tags: |
            type=raw,enable=${{github.event_name == 'push' && github.ref == 'refs/heads/nwiltsie-support-nextflow-24'}},value=test-${{ nextflow_version }}
            type=raw,enable=${{github.event_name == 'push' && github.ref == 'refs/heads/nwiltsie-support-nextflow-24'}},value=test-${{ nextflow_version }}-${{steps.date.outputs.date}}
