---
name: Build image

# Only rebuild when changes to the run-nextflow-tests/ folder are pushed to
# main
on:
  push:
    branches:
      - main
      - nwiltsie-nextflow-regression-action
    paths:
      - 'run-nextflow-tests/*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: A job to build and push a docker image
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - id: getversion
        uses: jbutcher5/read-yaml@1.6
        with:
          file: run-nextflow-tests/docker-metadata.yaml
          key-path: '["nextflow_version"]'

      - id: build-push
        uses: uclahs-cds/tool-Docker-action/build-release@nwiltsie-enable-subfolders
        with:
          metadata-file: run-nextflow-tests/docker-metadata.yaml
          context: run-nextflow-tests
          github-token: ${{ secrets.GITHUB_TOKEN }}
          custom-tags: |
            type=raw,enable=${{github.event_name == 'push'}},value=${{steps.getversion.outputs.data}}
            type=raw,enable=${{github.event_name == 'push'}},value=${{steps.getversion.outputs.data}}-${{github.run_number}}
