---
name: 'Nextflow tests'

on:
  workflow_call:

# Inspired by https://blog.aspect.dev/github-actions-dynamic-matrix
jobs:
  discover-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: listfiles
        shell: python
        run: |
          import json
          import os
          from pathlib import Path

          testfiles = [
              str(item) for item in
              Path(".").glob("**/configtest*.json")
          ]
          with open(os.environ.get("GITHUB_OUTPUT"),
                  mode="w", encoding="utf-8") as outfile:
              outfile.write(f"testfiles={json.dumps(testfiles)}\n")

    outputs:
      testfiles: ${{ steps.listfiles.outputs.testfiles }}

  runtests:
    runs-on: ubuntu-latest
    needs: discover-tests

    strategy:
      matrix:
        testfile: ${{ fromJSON(needs.discover-tests.outputs.testfiles) }}

    steps:
      - uses: actions/checkout@v4

      - shell: python
        run: |
          import sys
          from pathlib import Path

          print("${{ github.action_path }}")
          print(list(Path("${{ github.action_path }}").iterdir()))

          from configtest import NextflowConfigTest

          clean = NextflowConfigTest.from_file(
              "${{ matrix.testfile }}").check_results(
                  Path(".").resolve(),
                  "ghcr.io/uclahs-cds/nextflow-config-test:testing"
              )

          if not clean:
              sys.exit(1)
