---
name: 'Nextflow tests'

on:
  workflow_call:

# Inspired by https://blog.aspect.dev/github-actions-dynamic-matrix
jobs:
  discover-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: listfiles
        shell: python
        run: |
          import json
          import os
          from pathlib import Path

          testfiles = [
              str(item) for item in
              Path(".").glob("**/configtest*.json")
          ]
          with open(os.environ.get("GITHUB_OUTPUT"),
                  mode="w", encoding="utf-8") as outfile:
              outfile.write(f"testfiles={json.dumps(testfiles)}\n")

    outputs:
      testfiles: ${{ steps.listfiles.outputs.testfiles }}

  run-test:
    runs-on: ubuntu-latest
    needs: discover-tests

    strategy:
      fail-fast: false
      matrix:
        testfile: ${{ fromJSON(needs.discover-tests.outputs.testfiles) }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: dockertest
        run: |
          docker run \
            --rm \
            -e CI \
            -e GITHUB_OUTPUT \
            -v ${{ github.workspace}}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            ghcr.io/uclahs-cds/nextflow-config-test:23.10.0 \
              ${{ github.workspace }} \
              ${{ matrix.testfile }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.dockertest.outputs.archive_key }}
          path: ${{ steps.dockertest.outputs.archive_path }}
        if: ${{ !cancelled() }}
